Implement features
AnnGal/rs.android.task.4 pull request #2
Opened 2021-09-13 17:35 UTC by AnnGal

DB + Cursor + a bit of Navigation component

2021-09-14 18:32 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +    private val binding get() = _binding!!
Use nullable type instead of !!, try to avoid using it as it's more error-prone, and instead of using !!, why not use lateinit and simply name the var as binding and not _binding.

2021-09-14 18:33 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +
Try to avoid unnecessary spacing in the code)

2021-09-14 18:50 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +                            .setMessage(getString(R.string.delete_confirmation_question))
unnecessary spacing

2021-09-14 18:59 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +                        repoRoom.updateIdea(id = id!!.toLong(),
avoid using !!, use the alternative)

2021-09-14 19:01 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +                        database.updateIdeaViaCursor(id = id!!.toLong(),
!! -> use the alternative

2021-09-14 19:03 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +                    CoroutineScope(Dispatchers.Main).launch {
You can use withContext() here as it's already inside a coroutine scope)

2021-09-14 19:05 UTC, devesh-bhardwaj-21 commented on app/src/main/java/an/gal/android/goodideanote/idea_list/IdealListFragment.kt
>      private val binding get() = _binding!!
!!

2021-09-14 19:19 UTC, devesh-bhardwaj-21 requested changes
Great work Anya, you did a really good job!
Since I have only reviewed the code from here, I am presuming that the app is working fine as expected without any issues/crashes, please make sure of that.
I have added a few comments, try to fix your code based on my comments, they are most common for all the files, I may have missed a few so try to follow the same suggestions at all the places in the code and then push your changes so that I will approve and merge the code.
Thanks!

2021-09-15 11:48 UTC, AnnGal commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +    private val binding get() = _binding!!
Thanks! This is quite new for me. 
I saw this guide from google docs https://developer.android.com/topic/libraries/view-binding#fragments and never thought there was another approach for this.

2021-09-15 11:50 UTC, AnnGal commented on app/src/main/java/an/gal/android/goodideanote/idea_details/IdeaDetailsFragment.kt
> +                    CoroutineScope(Dispatchers.Main).launch {
Same here! Thanks for new knowledge - it is much better than start a new coroutine

2021-09-15 17:47 UTC, merged